name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Docker
        env:
          DOCKER_USERNAME: ${{ secrets.Name }}
          DOCKER_PASSWORD: ${{ secrets.Password }}
        run: |
          docker build -t $DOCKER_USERNAME/demo .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/demo

      - name: Send Notification to Google Chat
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: |
          MESSAGE="Build and deploy completed successfully!"
          curl -X POST -H 'Content-Type: application/json' \
          -d "{\"text\": \"${MESSAGE}\"}" \
          $GOOGLE_CHAT_WEBHOOK
