name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Docker
        env:
          DOCKER_USERNAME: ${{ secrets.jackulin123 }}
          DOCKER_PASSWORD: ${{ secrets.Jack@2205 }}
        run: |
          docker build -t jackulin123/demo .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push jackulin123/demo
